"""Cross-language reference tests against R implementations.

Fixtures in tests/fixtures/r/ are generated by experiments/r_reference/gen_fixtures.R
and committed, so these tests need no R installation. See that script for the
package versions and for how to build the CRAN-archived `neariso`.

References pinned here:
    stats::isoreg, Iso::pava   -> unweighted PAVA
    isotone::gpava             -> weighted PAVA
    cir::cirPAVA               -> centered isotonic regression
    neariso                    -> nearly-isotonic solution path
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "r"


def _load(name: str) -> dict:
    with open(FIXTURE_DIR / name) as fh:
        return json.load(fh)


PAVA = _load("pava_reference.json")["cases"]
_NI = _load("neariso_reference.json")
NEARISO = _NI["cases"]
NEARISO_OOR = _NI["out_of_range"]


def _case(name: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    c = PAVA[name]
    return (
        np.asarray(c["x"], dtype=float),
        np.asarray(c["y"], dtype=float),
        np.asarray(c["w"], dtype=float),
    )


# --------------------------------------------------------------------------- #
# Unweighted PAVA
# --------------------------------------------------------------------------- #

# `stats::isoreg` runs PAVA on the y-sequence ordered by x without first pooling
# tied x values, whereas sklearn/calibre pool ties into a single weighted point.
# The two therefore legitimately disagree when x has ties, so those cases are
# checked against the aggregated reference instead (see test_ties_are_pooled).
_UNTIED = ["simple", "binary", "all_zero", "all_one", "decreasing", "n1", "n2"]


@pytest.mark.parametrize("name", _UNTIED)
def test_isotonic_matches_r_isoreg(name):
    """calibre's IsotonicCalibrator reproduces stats::isoreg on distinct x."""
    from calibre import IsotonicCalibrator

    x, y, _ = _case(name)
    expected = np.asarray(PAVA[name]["isoreg"], dtype=float)

    got = IsotonicCalibrator().fit(x, y).transform(x)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-10)


@pytest.mark.parametrize("name", _UNTIED)
def test_r_references_agree_with_each_other(name):
    """Sanity check on the fixtures themselves: isoreg == Iso::pava."""
    a = np.asarray(PAVA[name]["isoreg"], dtype=float)
    b = np.asarray(PAVA[name]["iso_pava"], dtype=float)
    np.testing.assert_allclose(a, b, rtol=0, atol=1e-12)


# --------------------------------------------------------------------------- #
# Weighted PAVA
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", sorted(PAVA))
def test_weighted_pava_matches_r_gpava(name):
    """The shared weighted-PAVA primitive reproduces isotone::gpava.

    This is the primitive every constrained-isotonic calibrator is built on, so
    it is pinned independently of any calibrator.
    """
    from calibre._core import weighted_pava

    _, y, w = _case(name)
    expected = np.asarray(PAVA[name]["gpava_weighted"], dtype=float)

    got = weighted_pava(y, w)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-10)


@pytest.mark.parametrize("name", sorted(PAVA))
def test_weighted_r_references_agree(name):
    """Fixture sanity: isotone::gpava == Iso::pava with weights."""
    a = np.asarray(PAVA[name]["gpava_weighted"], dtype=float)
    b = np.asarray(PAVA[name]["iso_pava_weighted"], dtype=float)
    np.testing.assert_allclose(a, b, rtol=0, atol=1e-10)


@pytest.mark.parametrize("name", sorted(PAVA))
def test_unit_weights_reduce_to_unweighted(name):
    """weighted_pava with w=1 must equal the unweighted reference."""
    from calibre._core import weighted_pava

    _, y, _ = _case(name)
    expected = np.asarray(PAVA[name]["iso_pava"], dtype=float)
    got = weighted_pava(y, np.ones_like(y))
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-12)


# --------------------------------------------------------------------------- #
# Tie handling
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", sorted(PAVA))
def test_ties_are_pooled(name):
    """Tied x must be aggregated to one weighted point before fitting.

    Guards finding A8: building an interpolant on duplicated abscissae silently
    drops one of the tied points, and which one survives depends on an unstable
    argsort -- so the result is nondeterministic.
    """
    from calibre._core import aggregate_ties

    x, y, w = _case(name)
    ax, ay, aw = aggregate_ties(x, y, w)

    np.testing.assert_allclose(ax, np.asarray(PAVA[name]["agg_x"], dtype=float))
    np.testing.assert_allclose(ay, np.asarray(PAVA[name]["agg_y"], dtype=float))
    np.testing.assert_allclose(aw, np.asarray(PAVA[name]["agg_w"], dtype=float))


@pytest.mark.parametrize("name", sorted(PAVA))
def test_tied_x_output_is_deterministic(name):
    """Same inputs in a different row order must give the same fitted curve."""
    from calibre import IsotonicCalibrator

    x, y, _ = _case(name)
    if len(x) < 2:
        pytest.skip("permutation is meaningless for n < 2")

    grid = np.linspace(x.min(), x.max(), 25)
    base = IsotonicCalibrator().fit(x, y).transform(grid)

    rng = np.random.default_rng(0)
    for _ in range(5):
        p = rng.permutation(len(x))
        got = IsotonicCalibrator().fit(x[p], y[p]).transform(grid)
        np.testing.assert_allclose(got, base, rtol=0, atol=1e-12)


# --------------------------------------------------------------------------- #
# Centered isotonic regression
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", sorted(PAVA))
def test_centered_isotonic_matches_r_cirpava(name):
    """CenteredIsotonicCalibrator reproduces cir::cirPAVA on the unique-x grid."""
    from calibre import CenteredIsotonicCalibrator

    x, y, w = _case(name)
    expected = PAVA[name]["cir"]
    if expected is None:
        pytest.skip("cirPAVA produced no reference for this case")
    expected = np.asarray(expected, dtype=float)
    grid = np.asarray(PAVA[name]["cir_x"], dtype=float)

    got = CenteredIsotonicCalibrator().fit(x, y, sample_weight=w).transform(grid)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-8)


@pytest.mark.parametrize("name", sorted(PAVA))
def test_cir_knots_are_strictly_increasing(name):
    """CIR's guarantee: no two knots share a value, so no interior plateau.

    This is the package's headline claim, stated on the object CIR actually
    produces. Testing "no repeated value in transform(unique(x))" instead would
    be wrong: the terminal blocks are legitimately flat and can span many
    points, which is why the curve is only strictly monotone *between* the first
    and last knots.

    A plateau-preserving implementation satisfies calibre's current granularity
    test (ratio >= 0.003) while failing this one.
    """
    from calibre import CenteredIsotonicCalibrator

    x, y, w = _case(name)
    if len(np.unique(y)) < 2:
        pytest.skip("constant target: the curve is legitimately flat")

    cal = CenteredIsotonicCalibrator().fit(x, y, sample_weight=w)
    knots_x = cal.calibration_curve_.x
    knots_y = cal.calibration_curve_.y

    assert np.all(np.diff(knots_x) > 0), f"{name}: knot grid not increasing: {knots_x}"
    assert np.all(np.diff(knots_y) > 0), (
        f"{name}: CIR produced two knots at the same value, i.e. a plateau "
        f"survived the collapse: {knots_y}"
    )


@pytest.mark.parametrize("name", sorted(PAVA))
def test_cir_is_monotone_and_at_least_as_granular_as_isotonic(name):
    """CIR must stay monotone while producing no fewer distinct values than PAVA.

    The granularity claim reduces to this comparison, and it is the one the
    current suite never makes.
    """
    from calibre import CenteredIsotonicCalibrator, IsotonicCalibrator

    x, y, w = _case(name)
    grid = np.unique(x)

    cir = CenteredIsotonicCalibrator().fit(x, y, sample_weight=w).transform(grid)
    iso = IsotonicCalibrator().fit(x, y).transform(grid)

    assert np.all(np.diff(cir) >= -1e-12), f"{name}: CIR is not monotone: {cir}"
    assert len(np.unique(cir)) >= len(np.unique(iso)), (
        f"{name}: CIR gave {len(np.unique(cir))} distinct values, "
        f"isotonic gave {len(np.unique(iso))}"
    )


# --------------------------------------------------------------------------- #
# Nearly-isotonic regression
# --------------------------------------------------------------------------- #

# calibre minimizes  ||y - b||^2 + lam * sum max(0, b_i - b_{i+1})
# the paper minimizes (1/2)||y - b||^2 + lam_paper * sum max(0, ...)
# so lam_calibre = 2 * lam_paper.
LAMBDA_SCALE = 2.0


def _neariso_points():
    for name, case in NEARISO.items():
        for key, sol in case["solutions"].items():
            lam_paper = float(np.atleast_1d(sol["lambda_paper"])[0])
            if lam_paper <= 0:
                continue  # lambda=0 interpolates the data; nothing to pin
            yield pytest.param(name, key, id=f"{name}-{key}")


@pytest.mark.parametrize("name,key", list(_neariso_points()))
def test_nearly_isotonic_cvx_matches_r_neariso(name, key):
    """The CVXPY solver reproduces R's neariso at the matched lambda."""
    from calibre import NearlyIsotonicCalibrator

    case = NEARISO[name]
    y = np.asarray(case["y"], dtype=float)
    x = np.arange(1.0, len(y) + 1.0)

    sol = case["solutions"][key]
    lam_paper = float(np.atleast_1d(sol["lambda_paper"])[0])
    expected = np.asarray(sol["beta"], dtype=float)

    cal = NearlyIsotonicCalibrator(lam=LAMBDA_SCALE * lam_paper, method="cvx")
    got = cal.fit(x, y).transform(x)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-6)


@pytest.mark.parametrize("name,key", list(_neariso_points()))
def test_nearly_isotonic_path_matches_r_neariso(name, key):
    """The path solver must compute the estimator it names.

    Guards finding A6: the shipped path algorithm uses the raw level gap as its
    collision time instead of dividing by the difference in the groups' path
    slopes, and never lets group levels drift with lambda. It therefore does not
    solve the nearly-isotonic problem and disagrees with both R's neariso and
    calibre's own CVXPY solver.
    """
    from calibre import NearlyIsotonicCalibrator

    case = NEARISO[name]
    y = np.asarray(case["y"], dtype=float)
    x = np.arange(1.0, len(y) + 1.0)

    sol = case["solutions"][key]
    lam_paper = float(np.atleast_1d(sol["lambda_paper"])[0])
    expected = np.asarray(sol["beta"], dtype=float)

    cal = NearlyIsotonicCalibrator(lam=LAMBDA_SCALE * lam_paper, method="path")
    got = cal.fit(x, y).transform(x)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-6)


@pytest.mark.parametrize("name", sorted(NEARISO))
def test_nearly_isotonic_solvers_agree(name):
    """cvx and path must solve the same problem at the same lambda."""
    from calibre import NearlyIsotonicCalibrator

    y = np.asarray(NEARISO[name]["y"], dtype=float)
    x = np.arange(1.0, len(y) + 1.0)

    for lam in (0.05, 0.2, 0.5, 1.0):
        a = NearlyIsotonicCalibrator(lam=lam, method="cvx").fit(x, y).transform(x)
        b = NearlyIsotonicCalibrator(lam=lam, method="path").fit(x, y).transform(x)
        np.testing.assert_allclose(
            b, a, rtol=0, atol=1e-6, err_msg=f"{name}: solvers disagree at lam={lam}"
        )


@pytest.mark.parametrize("name", sorted(NEARISO))
def test_nearly_isotonic_attains_the_objective(name):
    """Both solvers must attain the documented objective's optimum.

    An independent check that does not rely on R: whatever the solver does, it
    cannot beat -- or fall short of -- the optimum of the objective it claims.
    """
    from calibre import NearlyIsotonicCalibrator

    y = np.asarray(NEARISO[name]["y"], dtype=float)
    x = np.arange(1.0, len(y) + 1.0)

    def objective(b, lam):
        return float(
            np.sum((y - b) ** 2) + lam * np.sum(np.maximum(0.0, b[:-1] - b[1:]))
        )

    for lam in (0.05, 0.2, 0.5, 1.0):
        ref = NearlyIsotonicCalibrator(lam=lam, method="cvx").fit(x, y).transform(x)
        got = NearlyIsotonicCalibrator(lam=lam, method="path").fit(x, y).transform(x)
        assert objective(got, lam) <= objective(ref, lam) + 1e-6, (
            f"{name}: path solver is suboptimal at lam={lam}: "
            f"{objective(got, lam):.8f} > {objective(ref, lam):.8f}"
        )


@pytest.mark.parametrize("key", sorted(NEARISO_OOR.get("solutions", {})))
def test_clipping_is_opt_out_able(key):
    """Output must not be silently clamped to [0, 1] with no way to disable it.

    Five of the calibrators apply a hard-coded post-hoc np.clip(., 0, 1). That
    makes them disagree with their own documented objective on any target
    straying outside the unit interval -- and a clipped solution is not the
    box-constrained optimum either, since the clip happens after the solve
    rather than as a constraint inside it.
    """
    from calibre import NearlyIsotonicCalibrator

    y = np.asarray(NEARISO_OOR["y"], dtype=float)
    x = np.arange(1.0, len(y) + 1.0)
    sol = NEARISO_OOR["solutions"][key]
    lam_paper = float(np.atleast_1d(sol["lambda_paper"])[0])
    expected = np.asarray(sol["beta"], dtype=float)
    assert np.any((expected < 0) | (expected > 1)), "fixture must exercise the clip"

    cal = NearlyIsotonicCalibrator(
        lam=LAMBDA_SCALE * lam_paper, method="cvx", clip_output=False
    )
    got = cal.fit(x, y).transform(x)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-6)


def test_lambda_scaling_is_documented():
    """calibre's lam is 2x the paper's lambda; the docstring must say so.

    The class docstring reproduces the paper's objective verbatim while the code
    omits the 1/2 on the squared-error term, so a lambda transferred from the
    paper delivers half the intended regularization.
    """
    from calibre import NearlyIsotonicCalibrator

    doc = (NearlyIsotonicCalibrator.__doc__ or "") + (
        NearlyIsotonicCalibrator.__init__.__doc__ or ""
    )
    lowered = doc.lower()
    assert "1/2" in doc or "\\frac{1}{2}" in doc or "twice" in lowered, (
        "NearlyIsotonicCalibrator's documented objective omits the 1/2 factor "
        "that the reference formulation carries, so `lam` is silently 2x the "
        "paper's lambda. Either match the paper's scaling or document the "
        "difference."
    )


# --------------------------------------------------------------------------- #
# Monotone P-spline vs R's scam
# --------------------------------------------------------------------------- #

_SCAM = _load("scam_reference.json")["cases"]


@pytest.mark.parametrize("name", sorted(_SCAM))
def test_monotone_spline_agrees_with_scam(name):
    """The monotone spline must track ``scam(bs="mpi")``.

    ``scam`` implements the same construction -- a B-spline basis with a discrete
    coefficient penalty, reparameterised so the coefficients increase (Pya & Wood
    2015). So it is the right external reference.

    A tight pointwise bound would be the wrong assertion, and measuring it showed
    why. ``scam`` selects its smoothing parameter by GCV while calibre
    cross-validates log-loss, so the two legitimately land on differently smoothed
    curves -- and on two of these three cases *calibre* achieves the lower
    in-sample log-loss (``steep``: 0.4122 vs 0.4160; ``logistic``: 0.60334 vs
    0.60335). Demanding pointwise agreement would penalise the better fit.

    Divergence concentrates where it should: at the boundaries, where the two
    packages' extrapolation conventions differ and the data is thinnest. On
    ``concave`` (true ``p = sqrt(x)``, so ``p -> 0`` steeply at the left edge) the
    curves differ by 0.117 at ``x = 0.001`` but only 0.060 in the interior.

    So what is checked is what is actually claimed: both fits are monotone, and
    they agree in the interior. Proper-score competitiveness is asserted separately
    by :func:`test_monotone_spline_log_loss_matches_scam`.
    """
    from calibre import SplineCalibrator

    case = _SCAM[name]
    x = np.asarray(case["x"], dtype=float)
    y = np.asarray(case["y"], dtype=float)
    grid = np.asarray(case["grid"], dtype=float)
    reference = np.asarray(case["fitted_grid"], dtype=float)

    cal = SplineCalibrator(n_knots=10, degree=3, random_state=0).fit(x, y)
    fitted = cal.transform(grid)

    assert np.all(np.diff(fitted) >= -1e-10), "calibre fit is not monotone"
    assert np.all(np.diff(reference) >= -1e-9), "scam reference is not monotone"

    interior = (grid >= np.quantile(x, 0.05)) & (grid <= np.quantile(x, 0.95))
    gap = float(np.max(np.abs(fitted[interior] - reference[interior])))
    assert gap < 0.08, f"{name}: interior curves differ by {gap:.4f}"

    mean_gap = float(np.mean(np.abs(fitted - reference)))
    assert mean_gap < 0.05, f"{name}: mean gap {mean_gap:.4f} across the range"


@pytest.mark.parametrize("name", sorted(_SCAM))
def test_monotone_spline_log_loss_matches_scam(name):
    """In-sample log-loss must be comparable to scam's, not merely finite."""
    from calibre import SplineCalibrator

    case = _SCAM[name]
    x = np.asarray(case["x"], dtype=float)
    y = np.asarray(case["y"], dtype=float)
    reference_loss = float(np.atleast_1d(case["logloss"])[0])

    fitted = SplineCalibrator(n_knots=10, degree=3, random_state=0).fit_transform(x, y)
    p = np.clip(fitted, 1e-12, 1 - 1e-12)
    ours = float(-np.mean(y * np.log(p) + (1 - y) * np.log1p(-p)))

    assert ours < reference_loss * 1.05, (
        f"{name}: log-loss {ours:.6f} vs scam {reference_loss:.6f}"
    )
