"""Cross-language reference tests against R implementations.

Fixtures in tests/fixtures/r/ are generated by experiments/r_reference/gen_fixtures.R
and committed, so these tests need no R installation. See that script for the
package versions and for how to build the CRAN-archived `neariso`.

References pinned here:
    stats::isoreg, Iso::pava   -> unweighted PAVA
    isotone::gpava             -> weighted PAVA
    cir::cirPAVA               -> centered isotonic regression
    neariso                    -> nearly-isotonic solution path
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "r"


def _load(name: str) -> dict:
    with (FIXTURE_DIR / name).open() as fh:
        return json.load(fh)


PAVA = _load("pava_reference.json")["cases"]
_NI = _load("neariso_reference.json")
NEARISO = _NI["cases"]
NEARISO_OOR = _NI["out_of_range"]


def _case(name: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    c = PAVA[name]
    return (
        np.asarray(c["x"], dtype=float),
        np.asarray(c["y"], dtype=float),
        np.asarray(c["w"], dtype=float),
    )


# --------------------------------------------------------------------------- #
# Unweighted PAVA
# --------------------------------------------------------------------------- #

# `stats::isoreg` runs PAVA on the y-sequence ordered by x without first pooling
# tied x values, whereas sklearn/calibre pool ties into a single weighted point.
# The two therefore legitimately disagree when x has ties, so those cases are
# checked against the aggregated reference instead (see test_ties_are_pooled).
_UNTIED = ["simple", "binary", "all_zero", "all_one", "decreasing", "n1", "n2"]


@pytest.mark.parametrize("name", _UNTIED)
def test_isotonic_matches_r_isoreg(name):
    """calibre's IsotonicCalibrator reproduces stats::isoreg on distinct x."""
    from calibre import IsotonicCalibrator

    x, y, _ = _case(name)
    expected = np.asarray(PAVA[name]["isoreg"], dtype=float)

    got = IsotonicCalibrator().fit(x, y).transform(x)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-10)


@pytest.mark.parametrize("name", _UNTIED)
def test_r_references_agree_with_each_other(name):
    """Sanity check on the fixtures themselves: isoreg == Iso::pava."""
    a = np.asarray(PAVA[name]["isoreg"], dtype=float)
    b = np.asarray(PAVA[name]["iso_pava"], dtype=float)
    np.testing.assert_allclose(a, b, rtol=0, atol=1e-12)


# --------------------------------------------------------------------------- #
# Weighted PAVA
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", sorted(PAVA))
def test_weighted_pava_matches_r_gpava(name):
    """The shared weighted-PAVA primitive reproduces isotone::gpava.

    This is the primitive every constrained-isotonic calibrator is built on, so
    it is pinned independently of any calibrator.
    """
    from calibre._core import weighted_pava

    _, y, w = _case(name)
    expected = np.asarray(PAVA[name]["gpava_weighted"], dtype=float)

    got = weighted_pava(y, w)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-10)


@pytest.mark.parametrize("name", sorted(PAVA))
def test_weighted_r_references_agree(name):
    """Fixture sanity: isotone::gpava == Iso::pava with weights."""
    a = np.asarray(PAVA[name]["gpava_weighted"], dtype=float)
    b = np.asarray(PAVA[name]["iso_pava_weighted"], dtype=float)
    np.testing.assert_allclose(a, b, rtol=0, atol=1e-10)


@pytest.mark.parametrize("name", sorted(PAVA))
def test_unit_weights_reduce_to_unweighted(name):
    """weighted_pava with w=1 must equal the unweighted reference."""
    from calibre._core import weighted_pava

    _, y, _ = _case(name)
    expected = np.asarray(PAVA[name]["iso_pava"], dtype=float)
    got = weighted_pava(y, np.ones_like(y))
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-12)


# --------------------------------------------------------------------------- #
# Tie handling
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", sorted(PAVA))
def test_ties_are_pooled(name):
    """Tied x must be aggregated to one weighted point before fitting.

    Guards finding A8: building an interpolant on duplicated abscissae silently
    drops one of the tied points, and which one survives depends on an unstable
    argsort -- so the result is nondeterministic.
    """
    from calibre._core import aggregate_ties

    x, y, w = _case(name)
    ax, ay, aw = aggregate_ties(x, y, w)

    np.testing.assert_allclose(ax, np.asarray(PAVA[name]["agg_x"], dtype=float))
    np.testing.assert_allclose(ay, np.asarray(PAVA[name]["agg_y"], dtype=float))
    np.testing.assert_allclose(aw, np.asarray(PAVA[name]["agg_w"], dtype=float))


@pytest.mark.parametrize("name", sorted(PAVA))
def test_tied_x_output_is_deterministic(name):
    """Same inputs in a different row order must give the same fitted curve."""
    from calibre import IsotonicCalibrator

    x, y, _ = _case(name)
    if len(x) < 2:
        pytest.skip("permutation is meaningless for n < 2")

    grid = np.linspace(x.min(), x.max(), 25)
    base = IsotonicCalibrator().fit(x, y).transform(grid)

    rng = np.random.default_rng(0)
    for _ in range(5):
        p = rng.permutation(len(x))
        got = IsotonicCalibrator().fit(x[p], y[p]).transform(grid)
        np.testing.assert_allclose(got, base, rtol=0, atol=1e-12)


# --------------------------------------------------------------------------- #
# Centered isotonic regression
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("name", sorted(PAVA))
def test_centered_isotonic_matches_r_cirpava(name):
    """CenteredIsotonicCalibrator reproduces cir::cirPAVA on the unique-x grid."""
    from calibre import CenteredIsotonicCalibrator

    x, y, w = _case(name)
    expected = PAVA[name]["cir"]
    if expected is None:
        pytest.skip("cirPAVA produced no reference for this case")
    expected = np.asarray(expected, dtype=float)
    grid = np.asarray(PAVA[name]["cir_x"], dtype=float)

    got = CenteredIsotonicCalibrator().fit(x, y, sample_weight=w).transform(grid)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-8)


@pytest.mark.parametrize("name", sorted(PAVA))
def test_cir_knots_are_strictly_increasing(name):
    """CIR's guarantee: no two knots share a value, so no interior plateau.

    This is the package's headline claim, stated on the object CIR actually
    produces. Testing "no repeated value in transform(unique(x))" instead would
    be wrong: the terminal blocks are legitimately flat and can span many
    points, which is why the curve is only strictly monotone *between* the first
    and last knots.

    A plateau-preserving implementation satisfies calibre's current granularity
    test (ratio >= 0.003) while failing this one.
    """
    from calibre import CenteredIsotonicCalibrator

    x, y, w = _case(name)
    if len(np.unique(y)) < 2:
        pytest.skip("constant target: the curve is legitimately flat")

    cal = CenteredIsotonicCalibrator().fit(x, y, sample_weight=w)
    knots_x = cal.calibration_curve_.x
    knots_y = cal.calibration_curve_.y

    assert np.all(np.diff(knots_x) > 0), f"{name}: knot grid not increasing: {knots_x}"
    assert np.all(np.diff(knots_y) > 0), (
        f"{name}: CIR produced two knots at the same value, i.e. a plateau "
        f"survived the collapse: {knots_y}"
    )


@pytest.mark.parametrize("name", sorted(PAVA))
def test_cir_is_monotone_and_at_least_as_granular_as_isotonic(name):
    """CIR must stay monotone while producing no fewer distinct values than PAVA.

    The granularity claim reduces to this comparison, and it is the one the
    current suite never makes.
    """
    from calibre import CenteredIsotonicCalibrator, IsotonicCalibrator

    x, y, w = _case(name)
    grid = np.unique(x)

    cir = CenteredIsotonicCalibrator().fit(x, y, sample_weight=w).transform(grid)
    iso = IsotonicCalibrator().fit(x, y).transform(grid)

    assert np.all(np.diff(cir) >= -1e-12), f"{name}: CIR is not monotone: {cir}"
    assert len(np.unique(cir)) >= len(np.unique(iso)), (
        f"{name}: CIR gave {len(np.unique(cir))} distinct values, "
        f"isotonic gave {len(np.unique(iso))}"
    )


# --------------------------------------------------------------------------- #
# Nearly-isotonic regression
# --------------------------------------------------------------------------- #


def _neariso_points():
    for name, case in NEARISO.items():
        for key, sol in case["solutions"].items():
            lam_paper = float(np.atleast_1d(sol["lambda_paper"])[0])
            if lam_paper <= 0:
                continue  # lambda=0 interpolates the data; nothing to pin
            yield pytest.param(name, key, id=f"{name}-{key}")


@pytest.mark.parametrize(("name", "key"), list(_neariso_points()))
def test_nearly_isotonic_path_matches_r_neariso(name, key):
    """The path solver must compute the estimator it names.

    Guards finding A6: the shipped path algorithm uses the raw level gap as its
    collision time instead of dividing by the difference in the groups' path
    slopes, and never lets group levels drift with lambda. It therefore does not
    solve the nearly-isotonic problem and disagrees with both R's neariso and
    calibre's own CVXPY solver.
    """
    from calibre import NearlyIsotonicCalibrator

    case = NEARISO[name]
    y = np.asarray(case["y"], dtype=float)
    x = np.arange(1.0, len(y) + 1.0)

    sol = case["solutions"][key]
    lam_paper = float(np.atleast_1d(sol["lambda_paper"])[0])
    expected = np.asarray(sol["beta"], dtype=float)

    cal = NearlyIsotonicCalibrator(lam=lam_paper)
    got = cal.fit(x, y).transform(x)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-6)


def _cvx_neariso(y, lam, weight=None):
    """Independent convex-program oracle for the documented objective."""
    import cvxpy as cp

    weight = np.ones_like(y) if weight is None else np.asarray(weight, dtype=float)
    beta = cp.Variable(len(y))
    objective = 0.5 * cp.sum(cp.multiply(weight, cp.square(y - beta)))
    objective += lam * cp.sum(cp.pos(beta[:-1] - beta[1:]))
    problem = cp.Problem(cp.Minimize(objective))
    problem.solve(
        solver=cp.OSQP,
        eps_abs=1e-9,
        eps_rel=1e-9,
        polishing=True,
    )
    assert problem.status == "optimal"
    return np.asarray(beta.value, dtype=float)


@pytest.mark.parametrize("name", sorted(NEARISO))
def test_nearly_isotonic_matches_independent_convex_program(name):
    """The path must attain the same solution as an independent optimizer."""
    from calibre import NearlyIsotonicCalibrator

    y = np.asarray(NEARISO[name]["y"], dtype=float)
    x = np.arange(1.0, len(y) + 1.0)

    for lam in (0.05, 0.2, 0.5, 1.0):
        expected = _cvx_neariso(y, lam)
        got = NearlyIsotonicCalibrator(lam=lam).fit(x, y).transform(x)
        np.testing.assert_allclose(
            got,
            expected,
            rtol=0,
            atol=1e-6,
            err_msg=f"{name}: path and convex program disagree at lam={lam}",
        )


@pytest.mark.parametrize("name", sorted(NEARISO))
def test_nearly_isotonic_attains_the_objective(name):
    """The path solver must attain the documented objective's optimum.

    An independent check that does not rely on R: whatever the solver does, it
    cannot beat -- or fall short of -- the optimum of the objective it claims.
    """
    from calibre import NearlyIsotonicCalibrator

    y = np.asarray(NEARISO[name]["y"], dtype=float)
    x = np.arange(1.0, len(y) + 1.0)

    def objective(b, lam):
        return float(
            0.5 * np.sum((y - b) ** 2) + lam * np.sum(np.maximum(0.0, b[:-1] - b[1:]))
        )

    for lam in (0.05, 0.2, 0.5, 1.0):
        ref = _cvx_neariso(y, lam)
        got = NearlyIsotonicCalibrator(lam=lam).fit(x, y).transform(x)
        assert objective(got, lam) <= objective(ref, lam) + 1e-6, (
            f"{name}: path solver is suboptimal at lam={lam}: "
            f"{objective(got, lam):.8f} > {objective(ref, lam):.8f}"
        )


@pytest.mark.parametrize("key", sorted(NEARISO_OOR.get("solutions", {})))
def test_clipping_is_opt_out_able(key):
    """Output must not be silently clamped to [0, 1] with no way to disable it.

    Five of the calibrators apply a hard-coded post-hoc np.clip(., 0, 1). That
    makes them disagree with their own documented objective on any target
    straying outside the unit interval -- and a clipped solution is not the
    box-constrained optimum either, since the clip happens after the solve
    rather than as a constraint inside it.
    """
    from calibre import NearlyIsotonicCalibrator

    y = np.asarray(NEARISO_OOR["y"], dtype=float)
    x = np.arange(1.0, len(y) + 1.0)
    sol = NEARISO_OOR["solutions"][key]
    lam_paper = float(np.atleast_1d(sol["lambda_paper"])[0])
    expected = np.asarray(sol["beta"], dtype=float)
    assert np.any((expected < 0) | (expected > 1)), "fixture must exercise the clip"

    cal = NearlyIsotonicCalibrator(lam=lam_paper, clip_output=False)
    got = cal.fit(x, y).transform(x)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-6)


def test_lambda_scaling_matches_the_paper():
    """The public lambda must use the source paper's scale without conversion."""
    from calibre import NearlyIsotonicCalibrator

    y = np.asarray(NEARISO["simple"]["y"], dtype=float)
    x = np.arange(y.size, dtype=float)
    solution = NEARISO["simple"]["solutions"]["bp02"]
    lam_paper = float(np.atleast_1d(solution["lambda_paper"])[0])
    expected = np.asarray(solution["beta"], dtype=float)

    got = NearlyIsotonicCalibrator(lam=lam_paper).fit_transform(x, y)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-6)


def test_weighted_nearly_isotonic_matches_independent_convex_program():
    """Observation weights must enter the same objective as the paper's loss."""
    from calibre import NearlyIsotonicCalibrator

    x = np.arange(7, dtype=float)
    y = np.array([0.1, 0.8, 0.2, 0.7, 0.4, 0.9, 0.6])
    weight = np.array([1.0, 4.0, 2.0, 1.0, 3.0, 2.0, 5.0])
    lam = 0.35

    expected = _cvx_neariso(y, lam, weight)
    got = NearlyIsotonicCalibrator(lam=lam).fit_transform(x, y, sample_weight=weight)
    np.testing.assert_allclose(got, expected, rtol=0, atol=1e-6)


def test_integer_weights_equal_literal_frequency_replication():
    """Frequency weights and repeated observations must define the same curve."""
    from calibre import NearlyIsotonicCalibrator

    x = np.arange(6, dtype=float)
    y = np.array([0.0, 1.0, 0.0, 1.0, 0.0, 1.0])
    weight = np.array([1, 3, 2, 4, 2, 1])
    grid = np.linspace(0.0, 5.0, 51)

    weighted = (
        NearlyIsotonicCalibrator(lam=0.5)
        .fit(x, y, sample_weight=weight)
        .transform(grid)
    )
    repeated = (
        NearlyIsotonicCalibrator(lam=0.5)
        .fit(np.repeat(x, weight), np.repeat(y, weight))
        .transform(grid)
    )
    np.testing.assert_allclose(weighted, repeated, rtol=0, atol=1e-12)


def test_data_scaled_auto_lambda_is_invariant_to_weight_units():
    """Changing weight units must scale lambda, not change the selected curve."""
    from calibre import NearlyIsotonicCalibrator

    x = np.linspace(0.0, 1.0, 60)
    y = (np.arange(60) % 4 == 0).astype(float)
    weight = np.linspace(1.0, 3.0, 60)
    grid = np.linspace(0.0, 1.0, 101)

    unit = NearlyIsotonicCalibrator(cv=3).fit(x, y, sample_weight=weight)
    scaled = NearlyIsotonicCalibrator(cv=3).fit(x, y, sample_weight=7.0 * weight)

    assert scaled.lam_ == pytest.approx(7.0 * unit.lam_)
    np.testing.assert_allclose(
        scaled.transform(grid), unit.transform(grid), rtol=0, atol=1e-10
    )


# --------------------------------------------------------------------------- #
# Monotone P-spline vs R's scam
# --------------------------------------------------------------------------- #

_SCAM = _load("scam_reference.json")["cases"]


@pytest.mark.parametrize("name", sorted(_SCAM))
def test_monotone_spline_agrees_with_scam(name):
    """The monotone spline must track the related ``scam(bs="mpi")`` model.

    Both methods use penalized monotone B-splines, but ``scam`` uses the nonlinear
    SCOP-spline parameterization and GCV smoothing selection of Pya & Wood (2015),
    while calibre uses hard nonnegative increments and cross-validated proper loss.
    It is therefore a behavioral external reference, not an implementation oracle.

    A tight pointwise bound would be the wrong assertion, and measuring it showed
    why. ``scam`` selects its smoothing parameter by GCV while calibre
    cross-validates log-loss, so the two legitimately land on differently smoothed
    curves -- and on two of these three cases *calibre* achieves the lower
    in-sample log-loss (``steep``: 0.4122 vs 0.4160; ``logistic``: 0.60334 vs
    0.60335). Demanding pointwise agreement would penalise the better fit.

    Divergence concentrates where it should: at the boundaries, where the two
    packages' extrapolation conventions differ and the data is thinnest. On
    ``concave`` (true ``p = sqrt(x)``, so ``p -> 0`` steeply at the left edge) the
    curves differ by 0.117 at ``x = 0.001`` but only 0.060 in the interior.

    So what is checked is what is actually claimed: both fits are monotone, and
    they agree in the interior. Proper-score competitiveness is asserted separately
    by :func:`test_monotone_spline_log_loss_matches_scam`.
    """
    from calibre import SplineCalibrator

    case = _SCAM[name]
    x = np.asarray(case["x"], dtype=float)
    y = np.asarray(case["y"], dtype=float)
    grid = np.asarray(case["grid"], dtype=float)
    reference = np.asarray(case["fitted_grid"], dtype=float)

    cal = SplineCalibrator(n_knots=10, degree=3, random_state=0).fit(x, y)
    fitted = cal.transform(grid)

    assert np.all(np.diff(fitted) >= -1e-10), "calibre fit is not monotone"
    assert np.all(np.diff(reference) >= -1e-9), "scam reference is not monotone"

    interior = (grid >= np.quantile(x, 0.05)) & (grid <= np.quantile(x, 0.95))
    gap = float(np.max(np.abs(fitted[interior] - reference[interior])))
    assert gap < 0.08, f"{name}: interior curves differ by {gap:.4f}"

    mean_gap = float(np.mean(np.abs(fitted - reference)))
    assert mean_gap < 0.05, f"{name}: mean gap {mean_gap:.4f} across the range"


@pytest.mark.parametrize("name", sorted(_SCAM))
def test_monotone_spline_log_loss_matches_scam(name):
    """In-sample log-loss must be comparable to scam's, not merely finite."""
    from calibre import SplineCalibrator

    case = _SCAM[name]
    x = np.asarray(case["x"], dtype=float)
    y = np.asarray(case["y"], dtype=float)
    reference_loss = float(np.atleast_1d(case["logloss"])[0])

    fitted = SplineCalibrator(n_knots=10, degree=3, random_state=0).fit_transform(x, y)
    p = np.clip(fitted, 1e-12, 1 - 1e-12)
    ours = float(-np.mean(y * np.log(p) + (1 - y) * np.log1p(-p)))

    assert ours < reference_loss * 1.05, (
        f"{name}: log-loss {ours:.6f} vs scam {reference_loss:.6f}"
    )


# --------------------------------------------------------------------------- #
# CORP reliability diagrams and score decompositions
# --------------------------------------------------------------------------- #

_CORP = _load("corp_reference.json")["cases"]


def _scalar(value) -> float:
    """Unwrap jsonlite's one-element arrays."""
    return float(np.atleast_1d(value)[0])


@pytest.mark.parametrize("name", sorted(_CORP))
def test_corp_cep_matches_reliabilitydiag(name):
    """PAV-recalibrated event probabilities must match R observation for observation.

    `reliabilitydiag` is the reference implementation for Dimitriadis, Gneiting &
    Jordan (2021). Agreement is required to machine precision, not approximately:
    both sides run the same PAV algorithm on the same pooled data, so any real
    difference is a bug rather than a numerical detail.
    """
    from calibre.evaluation import corp_reliability

    case = _CORP[name]
    x = np.asarray(case["x"], dtype=float)
    y = np.asarray(case["y"], dtype=float)

    diagram = corp_reliability(y, x)
    ours = np.interp(x, diagram.prediction_values, diagram.event_probabilities)

    np.testing.assert_allclose(
        ours, np.asarray(case["cep_pav"], dtype=float), atol=1e-12
    )


@pytest.mark.parametrize("name", sorted(_CORP))
def test_corp_brier_decomposition_matches_reliabilitydiag(name):
    """MCB, DSC and UNC must match R's summary() to machine precision.

    Only the Brier score is pinned: `reliabilitydiag` ships `brier` as its sole
    scoring rule and resolves `summary(score=)` through `get()`, so a
    hand-supplied log score does not return a mean log loss. calibre's log-score
    decomposition is verified algebraically in tests/test_evaluation.py, where
    the identity and the non-negativity of MCB and DSC are exact.
    """
    from calibre.evaluation import score_decomposition

    case = _CORP[name]
    x = np.asarray(case["x"], dtype=float)
    y = np.asarray(case["y"], dtype=float)
    reference = case["brier"]

    ours = score_decomposition(y, x, score="brier")

    for ours_key, r_key in (
        ("mean_score", "mean_score"),
        ("miscalibration", "miscalibration"),
        ("discrimination", "discrimination"),
        ("uncertainty", "uncertainty"),
    ):
        assert ours[ours_key] == pytest.approx(_scalar(reference[r_key]), abs=1e-12), (
            f"{name}: {ours_key} differs from reliabilitydiag"
        )
